name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/Release/TrevogaApp.exe
          config.json
        name: "Latest Auto Build"
        tag_name: "latest"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
